export const GalleryData = [
    {
        id:1,
        titile:"Car",
        image:"./images/a1.jpg"
    },
    {
        id:2,
        titile:"Car",
        image:"./images/a2.jpg"
    },
    {
        id:3,
        titile:"Car",
        image:"./images/a3.jpg"
    },

    {
        id:4,
        titile:"Car",
        image:"./images/a4.jpg"
    },
    {
        id:5,
        titile:"Car",
        image:"./images/a5.jpg"
    },
    {
        id:6,
        titile:"Car",
        image:"./images/a6.jpg"
    },
    {
        id:7,
        titile:"Car",
        image:"./images/a7.jpg"
    },


    {
        id:9,
        titile:"Bike",
        image:"./images/b1.jpg"
    },
    {
        id:10,
        titile:"Bike",
        image:"./images/b2.jpg"
    },
    {
        id:11,
        titile:"Cycle",
        image:"./images/c1.jpg"
    },
    {
        id:12,
        titile:"Cycle",
        image:"./images/c2.jpg"
    },

]